[develop]
script_dir=$base/lib/full_rviz_bridge

[install]
install_scripts=$base/lib/full_rviz_bridge

[options]
packages = find:
package_dir =
    = .

install_requires =
    rclpy
    nav_msgs
    geometry_msgs
    std_msgs

[options.packages.find]
where = .

[options.data_files]
share/ament_index/resource_index/packages = resource/full_rviz_bridge
share/full_rviz_bridge/launch = launch/rviz_robot_path.launch.py
